### PR TITLE
Fix: Reset color picker popover reference to enable repeated usage

### LINKED ISSUE #9: "C" shortcut doesn't work while annotating to change colors.

### PR DESCRIPTION
**Pull request by j-crowe**
### Summary
Fixes issue #9, where the color picker becomes unresponsive and cannot be reopened after the first use.

### Problem
The color picker popover was only working once per app session. After selecting a color and closing the popover, subsequent attempts to open it (via shortcut key or menu) would fail silently. This was caused by the app retaining a stale reference to the closed popover instance.

### Root Cause
The `colorPopover` property was never reset to `nil` after the popover closed
When `showColorPicker` was called again, it would try to show the existing (but closed) popover instead of creating a fresh one
This left the color picker in an unusable state

### Solution
Made `AppDelegate` conform to `NSPopoverDelegate`
Implemented `popoverWillClose(_:)` to reset `colorPopover = nil` when the popover closes
Updated `ColorPickerViewController` to close the popover via `performClose(nil)` properly
Made `colorPopover` optional (NSPopover?) for better type safety

### Testing

- [x]  Color picker opens on first use
- [x]  Color picker can be reopened multiple times after closing
- [x]  Works with both menu selection and keyboard shortcut
- [x]  Color selection and application still works correctly
- [x]  No memory leaks or retained references

---
Resolves #9 

## Summary by CodeRabbit

* **Bug Fixes**
  * Color picker popover now closes reliably, reducing flicker and preventing occasional crashes.
  * Safer handling of the color picker improves interaction stability.

* **Refactor**
  * Improved popover lifecycle management for better stability.
  * Adjusted board toggle behavior so overlay visibility timing is more predictable when toggling the board.

### CODE REVIEW

File: Annotate/AppDelegate.swift [hunk 1]
```diff
@@ -327,11 +332,11 @@ class AppDelegate: NSObject, NSApplicationDelegate, NSWindowDelegate {
         overlayWindows.values.forEach { window in
             window.overlayView.currentTool = tool
         }
-        showOverlay()
     }
 
     @objc func enableArrowMode(_ sender: NSMenuItem) {
         switchTool(to: .arrow)
+        showOverlay()
```
Comment (epilande) [inline Annotate/AppDelegate.swift]: This PR adds `showOverlay()` calls to all the tool switching methods (`enableArrowMode`, `enableLineMode`, etc.) but removes the `showOverlay()` call from the shared `switchTool(to:)` method. Could you clarify if these changes are related to the color picker fix?

Comment (j-crowe) [reply Annotate/AppDelegate.swift]: Thank you for the review @epilande .
Good callout. This was a mistake on my end when I thought the issue was related to the specific tool call.
It clearly shouldn't have any logical impact to call it once outside the tool call functions in `switchTool(to:)`.

I can update. I apologize for the poor hygiene here.

Comment (epilande) [reply Annotate/AppDelegate.swift]: No worries! Once that's cleaned up we can get this merged in

**Review by epilande — APPROVED** [review]
LGTM 👍 
Thanks for the contribution @j-crowe !!

**Comment by Nascent-Crescent** [comment]
Hi I just downloaded the latest version 1.3.1 but it seems like this issue persisted. After first use, both C (color) and W (width) window stopped appearing but they are still responsive to key press.
